apiVersion: v1
kind: Secret
metadata:
  name: microservice-secrets
type: Opaque
data:
  COUCHDB_USERNAME: YWRtaW4=  # base64-encoded "admin"
  COUCHDB_PASSWORD: c3R1ZGVudA==  # base64-encoded "student"
