apiVersion: v1                  
kind: Secret                    # Art des Kubernetes-Objekts, das erstellt wird (Secret)
metadata:
  name: microservice-secrets    # Der Name des Secrets
type: Opaque                    # Der Typ des Secrets (hier undurchsichtig, was bedeutet, dass der Inhalt undurchsichtig ist)
data:
  COUCHDB_USERNAME: YWRtaW4=   # base64-codierte "admin" für den Benutzernamen der Datenbank
  COUCHDB_PASSWORD: c3R1ZGVudA==  # base64-codierte "student" für das Passwort der Datenbank
